name: Enable GitHub Pages

on:
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  enable-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Enable GitHub Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
